version: "3"

networks:
  postgres-lan:
    driver: bridge

services:
  app:
    build: .
    ports: 
      - 8008:8000 
    restart: on-failure
    volumes:
      - app:/usr/src/app/
    depends_on:
      - postgres
    networks:
      - postgres-lan

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME:-dev_master}
      POSTGRES_USER: ${DB_USER:-benpro}
      POSTGRES_PASSWORD: ${password:-master}
    ports:
      - 5432
    networks:
      - postgres-lan

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-root@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-password}
    depends_on:
      - postgres
    ports:
      - "5050:80"
    networks:
      - postgres-lan
    restart: unless-stopped

volumes:
  app: